#!/usr/bin/env python3
"""
Module 45 Deliverable: ML CI/CD Toolkit

A comprehensive toolkit for ML CI/CD pipelines including:
- GitHub Actions workflow generation
- Validation gates for model deployment
- Test suite generators for ML projects
- Pipeline configuration management

Author: Neural Dojo
"""

import json
import os
import sys
from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Optional, Callable, Any


# =============================================================================
# CONSTANTS AND CONFIGURATION
# =============================================================================

STORAGE_DIR = Path(".ml_cicd_toolkit")
WORKFLOWS_DIR = STORAGE_DIR / "workflows"
TESTS_DIR = STORAGE_DIR / "tests"


class TriggerType(Enum):
    """CI/CD trigger types."""
    PUSH = "push"
    PULL_REQUEST = "pull_request"
    SCHEDULE = "schedule"
    WORKFLOW_DISPATCH = "workflow_dispatch"
    RELEASE = "release"


class WorkflowType(Enum):
    """Types of ML workflows."""
    PR_VALIDATION = "pr_validation"
    CONTINUOUS_INTEGRATION = "continuous_integration"
    CONTINUOUS_TRAINING = "continuous_training"
    MODEL_DEPLOYMENT = "model_deployment"
    DATA_VALIDATION = "data_validation"
    FULL_PIPELINE = "full_pipeline"


class GateStatus(Enum):
    """Validation gate status."""
    PASSED = "passed"
    FAILED = "failed"
    SKIPPED = "skipped"
    WARNING = "warning"


# =============================================================================
# DATA CLASSES
# =============================================================================

@dataclass
class WorkflowConfig:
    """Configuration for a GitHub Actions workflow."""
    name: str
    workflow_type: WorkflowType
    triggers: list = field(default_factory=list)
    python_version: str = "3.10"
    cache_pip: bool = True
    cache_models: bool = False
    run_lint: bool = True
    run_tests: bool = True
    run_model_tests: bool = False
    deploy_on_success: bool = False
    notify_slack: bool = False
    schedule_cron: Optional[str] = None
    environment: str = "ubuntu-latest"
    secrets_needed: list = field(default_factory=list)


@dataclass
class GateResult:
    """Result from a validation gate."""
    gate_name: str
    status: GateStatus
    message: str
    value: Optional[float] = None
    threshold: Optional[float] = None
    metadata: dict = field(default_factory=dict)


@dataclass
class ValidationReport:
    """Complete validation report."""
    model_name: str
    timestamp: str
    gates: list
    overall_status: GateStatus
    recommendation: str
    metadata: dict = field(default_factory=dict)


@dataclass
class TestConfig:
    """Configuration for test generation."""
    include_unit: bool = True
    include_data: bool = True
    include_model: bool = True
    include_integration: bool = False
    min_coverage: float = 0.80
    data_schema: dict = field(default_factory=dict)
    model_thresholds: dict = field(default_factory=dict)


# =============================================================================
# GITHUB ACTIONS WORKFLOW GENERATOR
# =============================================================================

class WorkflowGenerator:
    """Generates GitHub Actions workflows for ML projects."""

    def __init__(self):
        """Initialize the generator."""
        pass

    def generate(self, config: WorkflowConfig) -> str:
        """Generate a complete workflow YAML."""
        sections = [
            self._generate_header(config),
            self._generate_triggers(config),
            self._generate_env(config),
            self._generate_jobs(config),
        ]
        return "\n".join(sections)

    def _generate_header(self, config: WorkflowConfig) -> str:
        """Generate workflow header."""
        return f"""# {config.name}
# Generated by ML CI/CD Toolkit on {datetime.now().strftime('%Y-%m-%d')}
# Workflow Type: {config.workflow_type.value}

name: {config.name}
"""

    def _generate_triggers(self, config: WorkflowConfig) -> str:
        """Generate trigger configuration."""
        lines = ["on:"]

        for trigger in config.triggers:
            if trigger == TriggerType.PUSH:
                lines.extend([
                    "  push:",
                    "    branches: [main, develop]",
                    "    paths:",
                    "      - 'src/**'",
                    "      - 'tests/**'",
                    "      - 'requirements.txt'",
                ])
            elif trigger == TriggerType.PULL_REQUEST:
                lines.extend([
                    "  pull_request:",
                    "    branches: [main]",
                ])
            elif trigger == TriggerType.SCHEDULE and config.schedule_cron:
                lines.extend([
                    "  schedule:",
                    f"    - cron: '{config.schedule_cron}'",
                ])
            elif trigger == TriggerType.WORKFLOW_DISPATCH:
                lines.extend([
                    "  workflow_dispatch:",
                    "    inputs:",
                    "      force_deploy:",
                    "        description: 'Force deployment'",
                    "        required: false",
                    "        default: 'false'",
                ])
            elif trigger == TriggerType.RELEASE:
                lines.extend([
                    "  release:",
                    "    types: [published]",
                ])

        return "\n".join(lines) + "\n"

    def _generate_env(self, config: WorkflowConfig) -> str:
        """Generate environment variables."""
        lines = [
            "env:",
            f"  PYTHON_VERSION: '{config.python_version}'",
            "  PIP_CACHE_DIR: ~/.cache/pip",
        ]

        if config.cache_models:
            lines.append("  MODEL_CACHE_DIR: ~/.cache/models")

        return "\n".join(lines) + "\n"

    def _generate_jobs(self, config: WorkflowConfig) -> str:
        """Generate jobs based on workflow type."""
        if config.workflow_type == WorkflowType.PR_VALIDATION:
            return self._generate_pr_validation_jobs(config)
        elif config.workflow_type == WorkflowType.CONTINUOUS_INTEGRATION:
            return self._generate_ci_jobs(config)
        elif config.workflow_type == WorkflowType.CONTINUOUS_TRAINING:
            return self._generate_ct_jobs(config)
        elif config.workflow_type == WorkflowType.MODEL_DEPLOYMENT:
            return self._generate_deployment_jobs(config)
        elif config.workflow_type == WorkflowType.DATA_VALIDATION:
            return self._generate_data_validation_jobs(config)
        else:
            return self._generate_full_pipeline_jobs(config)

    def _generate_pr_validation_jobs(self, config: WorkflowConfig) -> str:
        """Generate PR validation jobs."""
        jobs = ["jobs:"]

        # Lint job
        if config.run_lint:
            jobs.extend([
                "  lint:",
                f"    runs-on: {config.environment}",
                "    steps:",
                "      - uses: actions/checkout@v4",
                "      - uses: actions/setup-python@v5",
                "        with:",
                "          python-version: ${{ env.PYTHON_VERSION }}",
                "      - name: Install linters",
                "        run: pip install ruff black mypy",
                "      - name: Run ruff",
                "        run: ruff check src/",
                "      - name: Check formatting",
                "        run: black --check src/",
                "      - name: Type check",
                "        run: mypy src/ --ignore-missing-imports",
                "",
            ])

        # Test job
        if config.run_tests:
            jobs.extend([
                "  test:",
                f"    runs-on: {config.environment}",
            ])

            if config.run_lint:
                jobs.append("    needs: lint")

            jobs.extend([
                "    steps:",
                "      - uses: actions/checkout@v4",
                "      - uses: actions/setup-python@v5",
                "        with:",
                "          python-version: ${{ env.PYTHON_VERSION }}",
            ])

            if config.cache_pip:
                jobs.extend([
                    "      - uses: actions/cache@v4",
                    "        with:",
                    "          path: ${{ env.PIP_CACHE_DIR }}",
                    "          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}",
                ])

            jobs.extend([
                "      - name: Install dependencies",
                "        run: pip install -r requirements.txt pytest pytest-cov",
                "      - name: Run tests",
                "        run: pytest tests/ -v --cov=src --cov-report=xml",
                "      - name: Upload coverage",
                "        uses: codecov/codecov-action@v3",
                "        with:",
                "          files: coverage.xml",
                "",
            ])

        # Model smoke test
        if config.run_model_tests:
            jobs.extend([
                "  model-test:",
                f"    runs-on: {config.environment}",
                "    needs: test",
                "    steps:",
                "      - uses: actions/checkout@v4",
                "      - uses: actions/setup-python@v5",
                "        with:",
                "          python-version: ${{ env.PYTHON_VERSION }}",
                "      - name: Install dependencies",
                "        run: pip install -r requirements.txt",
                "      - name: Quick model test",
                "        run: python -m src.test_model --quick",
                "",
            ])

        return "\n".join(jobs)

    def _generate_ci_jobs(self, config: WorkflowConfig) -> str:
        """Generate CI jobs."""
        return self._generate_pr_validation_jobs(config) + """
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .
      - name: Push to registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push myapp:${{ github.sha }}
"""

    def _generate_ct_jobs(self, config: WorkflowConfig) -> str:
        """Generate continuous training jobs."""
        return """jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Fetch new data
        run: python -m src.data.fetch --output data/new/
      - uses: actions/upload-artifact@v4
        with:
          name: training-data
          path: data/new/

  train:
    runs-on: ubuntu-latest
    needs: fetch-data
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: training-data
          path: data/new/
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train model
        run: |
          python -m src.train \\
            --data data/new/ \\
            --output models/candidate/
      - uses: actions/upload-artifact@v4
        with:
          name: candidate-model
          path: models/candidate/

  validate:
    runs-on: ubuntu-latest
    needs: train
    outputs:
      should_deploy: ${{ steps.validate.outputs.should_deploy }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: candidate-model
          path: models/candidate/
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Validate model
        id: validate
        run: |
          python -m src.validate_model \\
            --model models/candidate/ \\
            --output validation.json
          PASSED=$(python -c "import json; print(json.load(open('validation.json'))['passed'])")
          echo "should_deploy=$PASSED" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    if: needs.validate.outputs.should_deploy == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: candidate-model
          path: models/candidate/
      - name: Deploy model
        run: |
          echo "Deploying model..."
          # Add deployment commands here
"""

    def _generate_deployment_jobs(self, config: WorkflowConfig) -> str:
        """Generate deployment jobs."""
        return """jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t myapp:${{ github.sha }} .
      - name: Push image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push myapp:${{ github.sha }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging..."
          # kubectl set image deployment/app app=myapp:${{ github.sha }}

  test-staging:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Run smoke tests
        run: |
          echo "Testing staging deployment..."
          # curl -f http://staging.example.com/health

  deploy-production:
    runs-on: ubuntu-latest
    needs: test-staging
    environment: production
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # kubectl set image deployment/app app=myapp:${{ github.sha }}
"""

    def _generate_data_validation_jobs(self, config: WorkflowConfig) -> str:
        """Generate data validation jobs."""
        return """jobs:
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt great-expectations
      - name: Validate schema
        run: python -m src.data.validate_schema

  validate-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check data quality
        run: python -m src.data.validate_quality

  check-drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt evidently
      - name: Check for data drift
        run: python -m src.data.check_drift
"""

    def _generate_full_pipeline_jobs(self, config: WorkflowConfig) -> str:
        """Generate full pipeline jobs."""
        return self._generate_pr_validation_jobs(config) + """
  train:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Train model
        run: python -m src.train --output models/
      - uses: actions/upload-artifact@v4
        with:
          name: model
          path: models/

  validate:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: model
          path: models/
      - name: Validate model
        run: python -m src.validate --model models/

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        run: echo "Deploying..."
"""

    def save(self, config: WorkflowConfig, filename: str = None) -> Path:
        """Save workflow to file."""
        WORKFLOWS_DIR.mkdir(parents=True, exist_ok=True)

        if filename is None:
            filename = f"{config.workflow_type.value}.yml"

        content = self.generate(config)
        filepath = WORKFLOWS_DIR / filename

        with open(filepath, 'w') as f:
            f.write(content)

        return filepath


# =============================================================================
# VALIDATION GATES
# =============================================================================

class ValidationGate:
    """Base class for validation gates."""

    def __init__(self, name: str, required: bool = True):
        self.name = name
        self.required = required

    def check(self, context: dict) -> GateResult:
        raise NotImplementedError


class AccuracyGate(ValidationGate):
    """Check if model accuracy meets threshold."""

    def __init__(self, threshold: float = 0.85, name: str = "accuracy"):
        super().__init__(name)
        self.threshold = threshold

    def check(self, context: dict) -> GateResult:
        accuracy = context.get('metrics', {}).get('accuracy', 0)

        if accuracy >= self.threshold:
            return GateResult(
                gate_name=self.name,
                status=GateStatus.PASSED,
                message=f"Accuracy {accuracy:.3f} >= {self.threshold:.3f}",
                value=accuracy,
                threshold=self.threshold,
            )
        else:
            return GateResult(
                gate_name=self.name,
                status=GateStatus.FAILED,
                message=f"Accuracy {accuracy:.3f} < {self.threshold:.3f}",
                value=accuracy,
                threshold=self.threshold,
            )


class LatencyGate(ValidationGate):
    """Check if inference latency is acceptable."""

    def __init__(self, max_ms: float = 100, name: str = "latency"):
        super().__init__(name)
        self.max_ms = max_ms

    def check(self, context: dict) -> GateResult:
        latency = context.get('metrics', {}).get('latency_p99_ms', float('inf'))

        if latency <= self.max_ms:
            return GateResult(
                gate_name=self.name,
                status=GateStatus.PASSED,
                message=f"Latency {latency:.1f}ms <= {self.max_ms:.1f}ms",
                value=latency,
                threshold=self.max_ms,
            )
        else:
            return GateResult(
                gate_name=self.name,
                status=GateStatus.FAILED,
                message=f"Latency {latency:.1f}ms > {self.max_ms:.1f}ms",
                value=latency,
                threshold=self.max_ms,
            )


class RegressionGate(ValidationGate):
    """Check that model doesn't regress from baseline."""

    def __init__(
        self,
        metric: str = "accuracy",
        tolerance: float = 0.01,
        name: str = "no_regression",
    ):
        super().__init__(name)
        self.metric = metric
        self.tolerance = tolerance

    def check(self, context: dict) -> GateResult:
        current = context.get('metrics', {}).get(self.metric, 0)
        baseline = context.get('baseline_metrics', {}).get(self.metric, 0)

        min_allowed = baseline * (1 - self.tolerance)

        if current >= min_allowed:
            return GateResult(
                gate_name=self.name,
                status=GateStatus.PASSED,
                message=f"No regression: {current:.3f} >= {min_allowed:.3f}",
                value=current,
                threshold=min_allowed,
                metadata={"baseline": baseline},
            )
        else:
            return GateResult(
                gate_name=self.name,
                status=GateStatus.FAILED,
                message=f"Regression: {current:.3f} < {min_allowed:.3f}",
                value=current,
                threshold=min_allowed,
                metadata={"baseline": baseline},
            )


class MemoryGate(ValidationGate):
    """Check if model memory usage is acceptable."""

    def __init__(self, max_mb: float = 1000, name: str = "memory"):
        super().__init__(name)
        self.max_mb = max_mb

    def check(self, context: dict) -> GateResult:
        memory = context.get('metrics', {}).get('memory_mb', 0)

        if memory <= self.max_mb:
            return GateResult(
                gate_name=self.name,
                status=GateStatus.PASSED,
                message=f"Memory {memory:.0f}MB <= {self.max_mb:.0f}MB",
                value=memory,
                threshold=self.max_mb,
            )
        else:
            return GateResult(
                gate_name=self.name,
                status=GateStatus.FAILED,
                message=f"Memory {memory:.0f}MB > {self.max_mb:.0f}MB",
                value=memory,
                threshold=self.max_mb,
            )


class DataQualityGate(ValidationGate):
    """Check data quality metrics."""

    def __init__(
        self,
        max_missing_ratio: float = 0.01,
        max_duplicate_ratio: float = 0.01,
        name: str = "data_quality",
    ):
        super().__init__(name)
        self.max_missing_ratio = max_missing_ratio
        self.max_duplicate_ratio = max_duplicate_ratio

    def check(self, context: dict) -> GateResult:
        data_metrics = context.get('data_metrics', {})
        missing_ratio = data_metrics.get('missing_ratio', 0)
        duplicate_ratio = data_metrics.get('duplicate_ratio', 0)

        issues = []
        if missing_ratio > self.max_missing_ratio:
            issues.append(f"missing={missing_ratio:.2%}")
        if duplicate_ratio > self.max_duplicate_ratio:
            issues.append(f"duplicates={duplicate_ratio:.2%}")

        if issues:
            return GateResult(
                gate_name=self.name,
                status=GateStatus.FAILED,
                message=f"Data quality issues: {', '.join(issues)}",
                metadata=data_metrics,
            )
        else:
            return GateResult(
                gate_name=self.name,
                status=GateStatus.PASSED,
                message="Data quality checks passed",
                metadata=data_metrics,
            )


class ValidationPipeline:
    """Run model through validation gates."""

    def __init__(self, gates: list = None):
        self.gates = gates or []

    def add_gate(self, gate: ValidationGate):
        """Add a gate to the pipeline."""
        self.gates.append(gate)

    def validate(self, context: dict) -> ValidationReport:
        """Run all gates and generate report."""
        results = []
        all_passed = True

        for gate in self.gates:
            result = gate.check(context)
            results.append(result)

            if result.status == GateStatus.FAILED and gate.required:
                all_passed = False

        overall_status = GateStatus.PASSED if all_passed else GateStatus.FAILED
        recommendation = "Deploy" if all_passed else "Do not deploy - fix failing gates"

        return ValidationReport(
            model_name=context.get('model_name', 'unknown'),
            timestamp=datetime.now().isoformat(),
            gates=[asdict(r) for r in results],
            overall_status=overall_status,
            recommendation=recommendation,
            metadata=context.get('metadata', {}),
        )


# =============================================================================
# TEST GENERATOR
# =============================================================================

class TestGenerator:
    """Generate test files for ML projects."""

    def generate_unit_tests(self) -> str:
        """Generate unit test template."""
        return '''"""Unit tests for ML preprocessing and utilities."""
import pytest
import numpy as np
from src.preprocessing import normalize, tokenize

class TestNormalize:
    """Test normalization functions."""

    def test_normalize_zero_mean(self):
        """Output should have zero mean."""
        data = np.array([1, 2, 3, 4, 5])
        result = normalize(data)
        assert np.isclose(result.mean(), 0, atol=1e-7)

    def test_normalize_unit_variance(self):
        """Output should have unit variance."""
        data = np.array([1, 2, 3, 4, 5])
        result = normalize(data)
        assert np.isclose(result.std(), 1, atol=1e-7)

    def test_normalize_handles_constant(self):
        """Should handle constant arrays."""
        data = np.array([5, 5, 5, 5, 5])
        result = normalize(data)
        assert not np.any(np.isnan(result))


class TestTokenize:
    """Test tokenization functions."""

    def test_tokenize_basic(self):
        """Basic tokenization."""
        text = "Hello world"
        tokens = tokenize(text)
        assert len(tokens) == 2

    def test_tokenize_empty(self):
        """Empty input."""
        tokens = tokenize("")
        assert tokens == []
'''

    def generate_data_tests(self, schema: dict = None) -> str:
        """Generate data quality test template."""
        return '''"""Data quality tests."""
import pytest
import pandas as pd
from src.data import load_training_data

@pytest.fixture
def data():
    """Load data for tests."""
    return load_training_data()


class TestDataSchema:
    """Verify data schema."""

    def test_required_columns(self, data):
        """Required columns exist."""
        required = ['text', 'label']
        missing = set(required) - set(data.columns)
        assert not missing, f"Missing: {missing}"

    def test_no_nulls(self, data):
        """No nulls in required columns."""
        for col in ['text', 'label']:
            assert data[col].isnull().sum() == 0


class TestDataQuality:
    """Verify data quality."""

    def test_minimum_samples(self, data):
        """Minimum sample count."""
        assert len(data) >= 100

    def test_class_balance(self, data):
        """Reasonable class balance."""
        counts = data['label'].value_counts()
        ratio = counts.min() / counts.max()
        assert ratio >= 0.1, f"Imbalance: {ratio}"

    def test_no_duplicates(self, data):
        """No duplicate texts."""
        dup_ratio = data['text'].duplicated().mean()
        assert dup_ratio < 0.01
'''

    def generate_model_tests(self, thresholds: dict = None) -> str:
        """Generate model quality test template."""
        thresholds = thresholds or {"accuracy": 0.85, "latency_ms": 100}

        return f'''"""Model quality tests."""
import pytest
import time
from src.model import load_model, predict

@pytest.fixture(scope="module")
def model():
    """Load model once."""
    return load_model()


class TestModelAccuracy:
    """Verify model accuracy."""

    def test_accuracy_threshold(self, model):
        """Meets accuracy threshold."""
        from src.evaluate import evaluate
        metrics = evaluate(model)
        assert metrics['accuracy'] >= {thresholds.get('accuracy', 0.85)}


class TestModelLatency:
    """Verify inference speed."""

    def test_single_inference(self, model):
        """Single inference latency."""
        start = time.perf_counter()
        predict(model, "test input")
        latency_ms = (time.perf_counter() - start) * 1000
        assert latency_ms < {thresholds.get('latency_ms', 100)}


class TestModelRobustness:
    """Verify model robustness."""

    def test_empty_input(self, model):
        """Handles empty input."""
        result = predict(model, "")
        assert result is not None

    def test_long_input(self, model):
        """Handles long input."""
        result = predict(model, "x " * 1000)
        assert result is not None

    def test_special_characters(self, model):
        """Handles special characters."""
        result = predict(model, "Hello! @#$% \\n\\t")
        assert result is not None
'''

    def save_tests(self, config: TestConfig) -> dict:
        """Save test files."""
        TESTS_DIR.mkdir(parents=True, exist_ok=True)
        saved_files = {}

        if config.include_unit:
            path = TESTS_DIR / "test_unit.py"
            with open(path, 'w') as f:
                f.write(self.generate_unit_tests())
            saved_files['unit'] = path

        if config.include_data:
            path = TESTS_DIR / "test_data.py"
            with open(path, 'w') as f:
                f.write(self.generate_data_tests(config.data_schema))
            saved_files['data'] = path

        if config.include_model:
            path = TESTS_DIR / "test_model.py"
            with open(path, 'w') as f:
                f.write(self.generate_model_tests(config.model_thresholds))
            saved_files['model'] = path

        return saved_files


# =============================================================================
# PRESETS
# =============================================================================

WORKFLOW_PRESETS = {
    "pr-validation": WorkflowConfig(
        name="PR Validation",
        workflow_type=WorkflowType.PR_VALIDATION,
        triggers=[TriggerType.PULL_REQUEST],
        run_lint=True,
        run_tests=True,
        run_model_tests=False,
    ),
    "continuous-integration": WorkflowConfig(
        name="Continuous Integration",
        workflow_type=WorkflowType.CONTINUOUS_INTEGRATION,
        triggers=[TriggerType.PUSH, TriggerType.PULL_REQUEST],
        run_lint=True,
        run_tests=True,
        run_model_tests=True,
    ),
    "weekly-training": WorkflowConfig(
        name="Weekly Training",
        workflow_type=WorkflowType.CONTINUOUS_TRAINING,
        triggers=[TriggerType.SCHEDULE, TriggerType.WORKFLOW_DISPATCH],
        schedule_cron="0 2 * * 0",
        run_tests=False,
    ),
    "model-deployment": WorkflowConfig(
        name="Model Deployment",
        workflow_type=WorkflowType.MODEL_DEPLOYMENT,
        triggers=[TriggerType.RELEASE],
        deploy_on_success=True,
    ),
    "data-validation": WorkflowConfig(
        name="Data Validation",
        workflow_type=WorkflowType.DATA_VALIDATION,
        triggers=[TriggerType.PUSH, TriggerType.WORKFLOW_DISPATCH],
    ),
}

GATE_PRESETS = {
    "basic": [
        AccuracyGate(threshold=0.80),
        LatencyGate(max_ms=200),
    ],
    "strict": [
        AccuracyGate(threshold=0.90),
        LatencyGate(max_ms=100),
        MemoryGate(max_mb=500),
        RegressionGate(tolerance=0.005),
    ],
    "production": [
        AccuracyGate(threshold=0.85),
        LatencyGate(max_ms=100),
        MemoryGate(max_mb=1000),
        RegressionGate(tolerance=0.01),
        DataQualityGate(),
    ],
}


# =============================================================================
# DEMO FUNCTIONS
# =============================================================================

def demo_1_workflow_generation():
    """Demo 1: Generate GitHub Actions workflows."""
    print("=" * 70)
    print("DEMO 1: GITHUB ACTIONS WORKFLOW GENERATION")
    print("=" * 70)
    print()

    generator = WorkflowGenerator()

    print("📋 Available Workflow Presets:")
    print("-" * 40)
    for name, config in WORKFLOW_PRESETS.items():
        print(f"  • {name}")
        print(f"    Type: {config.workflow_type.value}")
        print(f"    Triggers: {[t.value for t in config.triggers]}")
    print()

    # Generate PR validation workflow
    print("🔧 Generating: PR Validation Workflow")
    print("-" * 40)

    config = WORKFLOW_PRESETS["pr-validation"]
    workflow = generator.generate(config)

    # Show first 40 lines
    lines = workflow.split('\n')
    for line in lines[:40]:
        print(f"  {line}")
    print(f"  ... ({len(lines) - 40} more lines)")
    print()

    path = generator.save(config, "pr-validation.yml")
    print(f"💾 Saved to: {path}")
    print()

    # Generate CT workflow
    print("🔧 Generating: Weekly Training Workflow")
    print("-" * 40)

    config = WORKFLOW_PRESETS["weekly-training"]
    workflow = generator.generate(config)

    lines = workflow.split('\n')
    for line in lines[:35]:
        print(f"  {line}")
    print(f"  ... ({len(lines) - 35} more lines)")
    print()

    path = generator.save(config, "weekly-training.yml")
    print(f"💾 Saved to: {path}")
    print()

    print("✅ Demo 1 complete!")


def demo_2_validation_gates():
    """Demo 2: Run validation gates on model metrics."""
    print("=" * 70)
    print("DEMO 2: MODEL VALIDATION GATES")
    print("=" * 70)
    print()

    print("📋 Available Gate Presets:")
    print("-" * 40)
    for name, gates in GATE_PRESETS.items():
        print(f"  • {name}: {[g.name for g in gates]}")
    print()

    # Simulate model metrics
    print("📊 Simulating Model Metrics:")
    print("-" * 40)

    good_metrics = {
        "model_name": "sentiment-v2",
        "metrics": {
            "accuracy": 0.92,
            "f1": 0.89,
            "latency_p99_ms": 45,
            "memory_mb": 450,
        },
        "baseline_metrics": {
            "accuracy": 0.88,
            "f1": 0.85,
        },
        "data_metrics": {
            "missing_ratio": 0.001,
            "duplicate_ratio": 0.002,
        },
    }

    print("  Good Model Metrics:")
    print(f"    Accuracy: {good_metrics['metrics']['accuracy']}")
    print(f"    Latency: {good_metrics['metrics']['latency_p99_ms']}ms")
    print(f"    Memory: {good_metrics['metrics']['memory_mb']}MB")
    print()

    # Run production gates
    print("🚦 Running Production Gates:")
    print("-" * 40)

    pipeline = ValidationPipeline(GATE_PRESETS["production"])
    report = pipeline.validate(good_metrics)

    for gate in report.gates:
        status = gate['status'].value if hasattr(gate['status'], 'value') else gate['status']
        status_icon = "✅" if status == 'passed' else "❌"
        print(f"  {status_icon} {gate['gate_name']}: {gate['message']}")

    print()
    print(f"📊 Overall: {report.overall_status.value.upper()}")
    print(f"📝 Recommendation: {report.recommendation}")
    print()

    # Now test with bad metrics
    print("📊 Testing with Failing Metrics:")
    print("-" * 40)

    bad_metrics = {
        "model_name": "sentiment-v2-bad",
        "metrics": {
            "accuracy": 0.75,  # Below threshold
            "latency_p99_ms": 250,  # Too slow
            "memory_mb": 450,
        },
        "baseline_metrics": {
            "accuracy": 0.88,
        },
        "data_metrics": {
            "missing_ratio": 0.001,
            "duplicate_ratio": 0.002,
        },
    }

    report = pipeline.validate(bad_metrics)

    for gate in report.gates:
        status = gate['status'].value if hasattr(gate['status'], 'value') else gate['status']
        status_icon = "✅" if status == 'passed' else "❌"
        print(f"  {status_icon} {gate['gate_name']}: {gate['message']}")

    print()
    print(f"📊 Overall: {report.overall_status.value.upper()}")
    print(f"📝 Recommendation: {report.recommendation}")
    print()

    print("✅ Demo 2 complete!")


def demo_3_test_generation():
    """Demo 3: Generate test suites for ML projects."""
    print("=" * 70)
    print("DEMO 3: TEST SUITE GENERATION")
    print("=" * 70)
    print()

    generator = TestGenerator()

    # Show test types
    print("📋 ML Test Types:")
    print("-" * 40)
    print("  • Unit Tests: Function-level testing")
    print("  • Data Tests: Schema and quality validation")
    print("  • Model Tests: Accuracy, latency, robustness")
    print()

    # Generate unit tests
    print("🔧 Generating: Unit Tests")
    print("-" * 40)
    unit_tests = generator.generate_unit_tests()
    lines = unit_tests.split('\n')
    for line in lines[:25]:
        print(f"  {line}")
    print(f"  ... ({len(lines) - 25} more lines)")
    print()

    # Generate data tests
    print("🔧 Generating: Data Quality Tests")
    print("-" * 40)
    data_tests = generator.generate_data_tests()
    lines = data_tests.split('\n')
    for line in lines[:25]:
        print(f"  {line}")
    print(f"  ... ({len(lines) - 25} more lines)")
    print()

    # Generate model tests
    print("🔧 Generating: Model Quality Tests")
    print("-" * 40)
    model_tests = generator.generate_model_tests({"accuracy": 0.90, "latency_ms": 50})
    lines = model_tests.split('\n')
    for line in lines[:25]:
        print(f"  {line}")
    print(f"  ... ({len(lines) - 25} more lines)")
    print()

    # Save all tests
    config = TestConfig(
        include_unit=True,
        include_data=True,
        include_model=True,
        model_thresholds={"accuracy": 0.85, "latency_ms": 100},
    )

    saved = generator.save_tests(config)
    print("💾 Saved test files:")
    for test_type, path in saved.items():
        print(f"  • {test_type}: {path}")
    print()

    print("✅ Demo 3 complete!")


def demo_4_full_setup():
    """Demo 4: Generate complete CI/CD setup for ML project."""
    print("=" * 70)
    print("DEMO 4: COMPLETE CI/CD SETUP")
    print("=" * 70)
    print()

    project_name = "sentiment-classifier"
    print(f"🚀 Setting up CI/CD for: {project_name}")
    print("-" * 40)

    workflow_gen = WorkflowGenerator()
    test_gen = TestGenerator()

    # Create project structure
    project_dir = STORAGE_DIR / "projects" / project_name / ".github" / "workflows"
    project_dir.mkdir(parents=True, exist_ok=True)

    tests_dir = STORAGE_DIR / "projects" / project_name / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)

    # Generate workflows
    print("\n1️⃣ Generating GitHub Actions Workflows...")

    workflows = {
        "PR Validation": WORKFLOW_PRESETS["pr-validation"],
        "Continuous Integration": WORKFLOW_PRESETS["continuous-integration"],
        "Weekly Training": WORKFLOW_PRESETS["weekly-training"],
    }

    for name, config in workflows.items():
        filename = config.workflow_type.value + ".yml"
        content = workflow_gen.generate(config)
        filepath = project_dir / filename
        with open(filepath, 'w') as f:
            f.write(content)
        print(f"   ✅ {name}: {filepath.name}")

    # Generate tests
    print("\n2️⃣ Generating Test Suite...")

    test_config = TestConfig(
        include_unit=True,
        include_data=True,
        include_model=True,
        model_thresholds={"accuracy": 0.85, "latency_ms": 100},
    )

    for test_type in ['unit', 'data', 'model']:
        if test_type == 'unit':
            content = test_gen.generate_unit_tests()
        elif test_type == 'data':
            content = test_gen.generate_data_tests()
        else:
            content = test_gen.generate_model_tests(test_config.model_thresholds)

        filepath = tests_dir / f"test_{test_type}.py"
        with open(filepath, 'w') as f:
            f.write(content)
        print(f"   ✅ test_{test_type}.py")

    # Generate validation config
    print("\n3️⃣ Generating Validation Config...")

    validation_config = {
        "gates": [
            {"type": "accuracy", "threshold": 0.85},
            {"type": "latency", "max_ms": 100},
            {"type": "memory", "max_mb": 1000},
            {"type": "regression", "tolerance": 0.01},
        ],
        "baseline_model": "models/production/model.pt",
        "test_dataset": "data/test/",
    }

    config_path = STORAGE_DIR / "projects" / project_name / "validation_config.json"
    with open(config_path, 'w') as f:
        json.dump(validation_config, f, indent=2)
    print(f"   ✅ validation_config.json")

    # Summary
    print("\n" + "=" * 70)
    print("📁 Generated Project Structure:")
    print("=" * 70)
    print(f"""
{project_name}/
├── .github/
│   └── workflows/
│       ├── pr_validation.yml      # PR checks
│       ├── continuous_integration.yml  # Full CI
│       └── continuous_training.yml     # Weekly retrain
├── tests/
│   ├── test_unit.py              # Unit tests
│   ├── test_data.py              # Data quality tests
│   └── test_model.py             # Model quality tests
└── validation_config.json        # Gate configuration
""")

    print("🚀 Quick Start Commands:")
    print("-" * 40)
    print("  # Run tests locally")
    print("  pytest tests/ -v")
    print()
    print("  # Validate model")
    print("  python -m src.validate --config validation_config.json")
    print()
    print("  # Push to trigger CI")
    print("  git push origin main")
    print()

    print("✅ Demo 4 complete!")
    print(f"\n📂 All files saved to: {STORAGE_DIR / 'projects' / project_name}")


def demo_5_pipeline_simulation():
    """Demo 5: Simulate a complete CI/CD pipeline run."""
    print("=" * 70)
    print("DEMO 5: PIPELINE SIMULATION")
    print("=" * 70)
    print()

    print("🔄 Simulating ML CI/CD Pipeline Run")
    print("=" * 70)
    print()

    # Stage 1: Code Quality
    print("📋 Stage 1: Code Quality Checks")
    print("-" * 40)

    checks = [
        ("Ruff (linting)", True, "No issues found"),
        ("Black (formatting)", True, "All files formatted correctly"),
        ("MyPy (type checking)", True, "No type errors"),
        ("Security scan", True, "No vulnerabilities detected"),
    ]

    for name, passed, message in checks:
        icon = "✅" if passed else "❌"
        print(f"  {icon} {name}: {message}")

    print()

    # Stage 2: Tests
    print("📋 Stage 2: Test Suite")
    print("-" * 40)

    tests = [
        ("Unit tests", 42, 42, 0),
        ("Data quality tests", 8, 8, 0),
        ("Model tests", 12, 11, 1),
        ("Integration tests", 5, 5, 0),
    ]

    total_passed = 0
    total_tests = 0

    for name, total, passed, failed in tests:
        total_tests += total
        total_passed += passed
        icon = "✅" if failed == 0 else "⚠️"
        print(f"  {icon} {name}: {passed}/{total} passed")

    print(f"\n  Total: {total_passed}/{total_tests} passed ({total_passed/total_tests*100:.0f}%)")
    print()

    # Stage 3: Model Validation
    print("📋 Stage 3: Model Validation Gates")
    print("-" * 40)

    gates = [
        ("Accuracy >= 0.85", 0.91, True),
        ("Latency < 100ms", 45, True),
        ("Memory < 1GB", 512, True),
        ("No regression > 1%", 0.3, True),
        ("Data quality OK", None, True),
    ]

    for name, value, passed in gates:
        icon = "✅" if passed else "❌"
        value_str = f"(value: {value})" if value else ""
        print(f"  {icon} {name} {value_str}")

    print()

    # Stage 4: Build
    print("📋 Stage 4: Build & Package")
    print("-" * 40)
    print("  ✅ Docker image built: myapp:abc123")
    print("  ✅ Image pushed to registry")
    print("  ✅ Image size: 1.2 GB")
    print()

    # Stage 5: Deploy
    print("📋 Stage 5: Deployment")
    print("-" * 40)
    print("  ✅ Deployed to staging")
    print("  ✅ Health check passed")
    print("  ✅ Smoke tests passed")
    print("  ⏳ Waiting for production approval...")
    print()

    # Summary
    print("=" * 70)
    print("📊 PIPELINE SUMMARY")
    print("=" * 70)
    print(f"""
  Status: ✅ SUCCESS
  Duration: 12m 34s

  Stages:
  ✅ Code Quality    (45s)
  ✅ Test Suite      (3m 12s)
  ✅ Model Validation (2m 45s)
  ✅ Build & Package  (4m 22s)
  ✅ Deploy Staging   (2m 10s)

  Artifacts:
  • Docker Image: myapp:abc123
  • Test Report: test-results.xml
  • Coverage: 87%
  • Model Metrics: metrics.json

  Ready for production deployment!
""")

    print("✅ Demo 5 complete!")


def print_usage():
    """Print usage information."""
    print("""
ML CI/CD Toolkit - Automate ML Pipelines

Usage: python deliverable_ml_cicd_toolkit.py <command>

Commands:
  demo1    Generate GitHub Actions workflows
  demo2    Run model validation gates
  demo3    Generate test suites
  demo4    Complete CI/CD setup for project
  demo5    Simulate pipeline run

Examples:
  python deliverable_ml_cicd_toolkit.py demo1
  python deliverable_ml_cicd_toolkit.py demo4
""")


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print_usage()
        return

    STORAGE_DIR.mkdir(parents=True, exist_ok=True)

    command = sys.argv[1].lower()

    if command == "demo1":
        demo_1_workflow_generation()
    elif command == "demo2":
        demo_2_validation_gates()
    elif command == "demo3":
        demo_3_test_generation()
    elif command == "demo4":
        demo_4_full_setup()
    elif command == "demo5":
        demo_5_pipeline_simulation()
    elif command in ["help", "-h", "--help"]:
        print_usage()
    else:
        print(f"Unknown command: {command}")
        print_usage()


if __name__ == "__main__":
    main()
